variables:
   Depot.Tools.Win.Toolchain: 0

jobs:
- job: Windows
  pool:
    name: 'AvaloniaPool'
  steps:

  - task: CmdLine@2
    displayName: 'Bootstrap'
    inputs:
      script: |
        python scripts/bootstrap.py
  
  - task: CmdLine@2
    displayName: 'GClient Sync'
    inputs:
      script: |
        gclient sync
      
  - task: CmdLine@2
    displayName: 'Generate Ninja (x64)'
    inputs:
      script: |
        gn gen out/x64

  - task: CmdLine@2
    displayName: 'Build Angle (x64)'
    inputs:
      script:  |
        autoninja -C out/x64

  - task: CmdLine@2
    displayName: 'Generate Ninja (x86)'
    inputs:
      script: |
        gn gen out/x86

  - task: CmdLine@2
    displayName: 'Build Angle (x86)'
    inputs:
      script:  |
        autoninja -C out/x86

  - task: CmdLine@2
    displayName: 'Generate Ninja (arm64)'
    inputs:
      script: |
        gn gen out/arm64

  - task: CmdLine@2
    displayName: 'Build Angle (arm64)'
    inputs:
      script:  |
        autoninja -C out/arm64

  - task: CmdLine@2
    displayName: 'Generate Nuget Package'
    inputs:
      script:  |
        dotnet pack -c Release $(Build.SourcesDirectory)/nuget/Avalonia.Angle.Windows.Natives.csproj

  - task: CmdLine@2
    displayName: 'Clear Output Dir'
    inputs:
      script:  |
        rmdir /Q /S artifacts

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/nuget/bin/Release/'
      contents: '*.nupkg' 
      targetFolder: '$(Build.SourcesDirectory)/artifacts/nuget'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/out/x64'
      contents: '*.pdb' 
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/x64'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/out/x86'
      contents: '*.pdb' 
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/x86'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/out/arm64'
      contents: '*.pdb' 
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin/arm64'
        
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/artifacts/nuget'
      artifactName: 'Nuget'
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/artifacts/bin'
      artifactName: 'PDBs'
    condition: succeeded()



