variables:
   Depot.Tools.Win.Toolchain: 0

jobs:
- job: Windows
  pool:
    name: 'AvaloniaPool'
  steps:

  - task: CmdLine@2
    displayName: 'Bootstrap'
    inputs:
      script: |
        python scripts/bootstrap.py
  
  - task: CmdLine@2
    displayName: 'GClient Sync'
    inputs:
      script: |
        gclient sync
      
  - task: CmdLine@2
    displayName: 'Generate Ninja'
    inputs:
      script: |
        gn gen out/x64

  - task: CmdLine@2
    displayName: 'Build Angle'
    inputs:
      script:  |
        autoninja -C out/x64

  - task: CmdLine@2
    displayName: 'Generate Ninja'
    inputs:
      script: |
        gn gen out/x86

  - task: CmdLine@2
    displayName: 'Build Angle'
    inputs:
      script:  |
        autoninja -C out/x86

  - task: CmdLine@2
    displayName: 'Generate Ninja'
    inputs:
      script: |
        gn gen out/arm64

  - task: CmdLine@2
    displayName: 'Build Angle'
    inputs:
      script:  |
        autoninja -C out/arm64

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/out/Release'
      contents: '*' 
      targetFolder: '$(Build.SourcesDirectory)/artifacts/bin'
        
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/artifacts/bin'
      artifactName: 'Angle'
    condition: succeeded()



