variables:
   Depot.Tools.Win.Toolchain: 0

jobs:
- job: Windows
  pool:
    name: 'AvaloniaPool'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
    displayName: 'Use Python 2.7'

  - task: CmdLine@2
    displayName: 'Prepare Sources'
    inputs:
      script: |
        python scripts/bootstrap.py
        gclient sync
      
  - task: CmdLine@2
    displayName: 'Generate Ninja'
    inputs:
      script: |
        gn gen out/Release

  - task: CmdLine@2
    displayName: 'Build Angle'
    inputs:
      script:  |
        autoninja target_cpu="x64" is_debug=false -j8 -C out/Release



