variables:
   Depot.Tools.Win.Toolchain: 0

jobs:
- job: Windows
  pool:
    name: 'AvaloniaPool'
  steps:

  - task: CmdLine@2
    displayName: 'Bootstrap'
    inputs:
      script: |
        python scripts/bootstrap.py
  
  - task: CmdLine@2
    displayName: 'GClient Sync'
    inputs:
      script: |
        gclient sync
      
  - task: CmdLine@2
    displayName: 'Generate Ninja'
    inputs:
      script: |
        gn gen out/Release

  - task: CmdLine@2
    displayName: 'Build Angle'
    inputs:
      script:  |
        autoninja -C out/Release

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/out/Release'
      artifactName: 'Angle'
    condition: succeeded()



