variables:
   Depot.Tools.Win.Toolchain: 0

jobs:
- job: Windows
  pool:
    name: 'AvaloniaPool'
  steps:

  - task: CmdLine@2
    displayName: 'Bootstrap'
    inputs:
      script: |
        python scripts/bootstrap.py
  
  - task: CmdLine@2
    displayName: 'GClient Sync'
    inputs:
      script: |
        gclient sync

  - task: CmdLine@2
    displayName: 'Generate Ninja (arm64)'
    inputs:
      script: |
        gn gen out/arm64 --args="is_debug=false is_clang=false target_cpu=\"arm64\" dcheck_always_on=false angle_enable_vulkan=false angle_enable_gl=false angle_enable_null=false" 

  - task: CmdLine@2
    displayName: 'Build Angle (arm64)'
    inputs:
      script:  |
        autoninja -C out/arm64 libGLESv2.dll.lib
      
  - task: CmdLine@2
    displayName: 'Generate Ninja (x64)'
    inputs:
      script: |
        gn gen out/x64 --args="is_debug=false is_clang=false target_cpu=\"x64\"  dcheck_always_on=false angle_enable_vulkan=false angle_enable_gl=false angle_enable_null=false"

  - task: CmdLine@2
    displayName: 'Build Angle (x64)'
    inputs:
      script:  |
        autoninja -C out/x64 libGLESv2.dll.lib

  - task: CmdLine@2
    displayName: 'Generate Ninja (x86)'
    inputs:
      script: |
        gn gen out/x86 --args="is_debug=false is_clang=false target_cpu=\"x86\" dcheck_always_on=false angle_enable_vulkan=false angle_enable_gl=false angle_enable_null=false"

  - task: CmdLine@2
    displayName: 'Build Angle (x86)'
    inputs:
      script:  |
        autoninja -C out/x86 libGLESv2.dll.lib

  - task: CmdLine@2
    displayName: 'Prefix DLLs'
    inputs:
      script:  |
        ren .\out\arm64\libGLESv2.dll av_libGLESv2.dll
        ren .\out\x64\libGLESv2.dll av_libGLESv2.dll
        ren .\out\x86\libGLESv2.dll av_libGLESv2.dll

  - task: CmdLine@2
    displayName: 'Clear Artifacts Dir'
    inputs:
      script:  |
        rmdir /Q /S artifacts
        rmdir /Q /s nuget\bin

  - task: CmdLine@2
    displayName: 'Generate Nuget Package'
    inputs:
      script:  |
        dotnet pack -c Release $(Build.SourcesDirectory)/nuget/Avalonia.Angle.Windows.Natives.csproj

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/nuget/bin/Release/'
      contents: '*.nupkg' 
      targetFolder: '$(Build.SourcesDirectory)/artifacts/nuget'
        
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/artifacts/nuget'
      artifactName: 'Nuget'
    condition: succeeded()



